apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport-service
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30171
  selector:
    app: postgres