apiVersion: v1
kind: Service
metadata:
  name: postgres-lb-service
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
    - port: 54321
      targetPort: 5432
  selector:
    app: postgres